/**
 * 1000+ word list for generating random 3-word game names.
 * Creates a list of 1000+ words and randomly chooses 3
 * Words generated from: www.randomlists.com/random-words
 */

const words = [
  "brief","puzzling","shy","position","instrument","tremble","probable","regret",
  "beef","skin","nut","creepy","versed","umbrella","far","egg","open","mixed",
  "debonair","aboriginal","chew","airplane","astonishing","bathe","basin","brash",
  "typical","history","tightfisted","shop","absurd","concerned","needy","entertaining",
  "jolly","finicky","expand","agonizing","hammer","sheep","guarded","drab","weak",
  "interest","secret","servant","stem","endurable","substance","grade","system","arch",
  "oranges","wobble","wait","complex","brush","orange","injure","milky","miscreant",
  "low","mountain","cooing","chivalrous","art","include","writing","grease","tendency",
  "petite","bashful","pet","nonchalant","cherry","lie","whisper","try","descriptive",
  "popcorn","dashing","telephone","hushed","colour","lacking","tramp","common","wander",
  "thirsty","miss","feigned","actually","tender","afternoon","leg","capable","infamous",
  "crayon","attraction","baseball","inexpensive","drag","crack","face","coherent","early",
  "late","elfin","produce","bent","stereotyped","bulb","stimulating","receive","remember",
  "delight","amusement","haircut","deep","cooperative","bump","railway","juggle",
  "ludicrous","automatic","useless","overt","understood","sail","suggestion","concentrate",
  "scorch","nifty","tail","obtain","fearless","vigorous","share","scene","judicious",
  "basket","wet","gratis","nonstop","icy","base","dog","pretend","bomb","lush",
  "destruction","vacation","cushion","lively","cheap","weight","unkempt","legal","boil",
  "spill","receptive","flesh","secretary","crow","steer","zealous","smoggy","curly",
  "tired","grass","discussion","mysterious","tie","passenger","perpetual","whirl","root",
  "clam","part","wandering","necessary","uppity","dead","mindless","peck","love",
  "shallow","fat","remind","adorable","axiomatic","zany","famous","women","busy","sleepy",
  "divide","illustrious","berserk","head","strong","clever","adventurous","wanting","start",
  "fax","spoon","guess","cultured","sweltering","worry","vegetable","introduce","roasted",
  "fact","sparkling","new","kaput","functional","spell","symptomatic","berry","observant",
  "pink","hurt","defective","reading","dark","end","soft","wiry","stitch","whistle",
  "explode","hop","houses","poised","horn","fragile","vagabond","wrestle","various","night",
  "file","flagrant","capricious","type","valuable","dust","blade","lewd","analyze","boot",
  "wrench","nine","treatment","action","mean","gate","kitty","hapless","school","picture",
  "whimsical","woebegone","borrow","queue","provide","annoyed","aberrant","repair","parcel",
  "honey","three","sort","icky","waste","vengeful","coordinated","fix","rings","wound",
  "mice","cent","rake","trains","point","lock","uninterested","beginner","juice","succeed",
  "prickly","gigantic","elastic","present","donkey","rice","eyes","sand","fold","place",
  "rural","cure","glorious","mix","numberless","fabulous","zipper","tempt","team","vein",
  "pollution","cakes","energetic","curl","connection","bait","ill-informed","fence","men",
  "memory","x-ray","majestic","inform","thought","cow","pocket","enter","inject","mug",
  "tremendous","screeching","cover","ablaze","church","fail","toes","lake","bizarre",
  "mammoth","tacky","ossified","waves","toothpaste","devilish","intend","raspy","unruly",
  "unwieldy","receipt","acoustics","pumped","periodic","soak","well-to-do","responsible",
  "decisive","tranquil","furry","sable","efficacious","acid","trip","abrasive","behave",
  "unusual","unite","stare","mom","unnatural","brass","greet","quack","books","thoughtful",
  "frail","squirrel","toothbrush","edge","plate","stale","calm","competition","cheerful",
  "building","known","yarn","efficient","equal","fascinated","supreme","pastoral",
  "embarrass","apparel","handle","brake","parched","eggnog","yak","taboo","pause","slave",
  "bite","bitter","dysfunctional","moan","selection","applaud","stupid","oval","calculating",
  "silky","chess","invention","liquid","spray","filthy","bear","troubled","unable","morning",
  "laughable","mouth","hypnotic","married","bag","public","pie","disagreeable","zesty",
  "wipe","spectacular","wren","knowledgeable","invent","ambiguous","ahead","theory","plants",
  "hurry","deserve","continue","permissible","badge","verdant","healthy","happy","grandiose",
  "eye","spooky","dime","iron","cat","horses","launch","reflective","turn","advise","dear",
  "imperfect","bewildered","ceaseless","didactic","aloof","victorious","paddle","jewel",
  "channel","butter","acceptable","scratch","cave","auspicious","grouchy","utter",
  "inquisitive","muddle","unknown","knowing","delightful","familiar","stiff","sincere",
  "undress","deliver","prevent","male","rose","wooden","flood","stone","sisters",
  "basketball","neat","offer","wise","boring","interesting","determined","creature","boat",
  "hill","bow","robust","cast","territory","time","fetch","meat","jumbled","abject","line",
  "list","useful","develop","gold","crash","romantic","exercise","achiever","awake","guitar",
  "elegant","strange","clammy","skate","perform","ghost","resolute","grandfather","delicious",
  "wonderful","divergent","acidic","program","humor","stamp","ignorant","general","club",
  "toad","toothsome","foamy","sick","industrious","class","cactus","weather","cobweb",
  "downtown","apathetic","advertisement","dinosaurs","afford","guide","opposite","writer",
  "embarrassed","tree","income","scandalous","activity","internal","guiltless","whip",
  "unlock","heavy","group","shelter","madly","painstaking","deer","bike","roll","mushy",
  "trucks","add","upset","tick","fill","boundary","tap","travel","visitor","rinse","comb",
  "dinner","exuberant","square","box","unpack","marble","lip","unsuitable","force","thread",
  "station","mark","mind","window","fierce","talented","teaching","addicted","sweater",
  "appliance","obscene","stay","quiver","uptight","acrid","stop","wasteful","smile","house",
  "digestion","frog","accessible","punch","utopian","thankful","tame","previous","shame",
  "outgoing","trouble","beautiful","wing","tire","tasteless","abhorrent","burst","alive",
  "evanescent","rustic","zippy","pump","abstracted","crib","jam","cry","toys","profuse",
  "knot","fear","rate","nerve","oil","surround","ignore","chubby","calculate","zephyr",
  "ratty","volatile","statement","hungry","slow","immense","show","religion","cars","yoke",
  "ruin","flashy","race","sheet","swing","spark","marry","groan","flower","jump","ban",
  "weigh","rude","current","blush","cough","old","rifle","harmonious","trashy","tenuous",
  "harbor","expert","sordid","knit","bells","things","classy","grin","slip","fixed","fish",
  "tow","space","strip","dramatic","trust","helpful","language","request","panicky","rapid",
  "gainful","push","disillusioned","ship","halting","rhetorical","snails","hilarious",
  "robin","magic","tested","cable","outrageous","wretched","exclusive","vase","tiresome",
  "bedroom","work","undesirable","aboard","royal","rebel","change","unbiased","mailbox",
  "ray","wink","rail","lamp","fallacious","sad","glove","death","harm","pear","squeal",
  "pathetic","scared","broad","big","defeated","color","recess","friction","collar","shave",
  "seemly","protest","friends","handy","signal","warlike","befitting","hospital","silly",
  "yielding","stew","retire","copy","left","tawdry","inconclusive","turkey","even","plug",
  "lucky","governor","sophisticated","flight","afraid","creator","materialistic","coat",
  "macabre","thumb","cemetery","equable","motion","future","border","measly","observe",
  "close","front","well-off","tease","voracious","rigid","faded","cub","teeth","lying",
  "minor","long-term","waggish","damaging","verse","year","boundless","gorgeous","minister",
  "rule","squash","person","join","argument","fresh","insidious","notice","pets","yummy",
  "free","average","melodic","crime","whispering","hope","lethal","help","bouncy",
  "quizzical","earthquake","ruddy","bury","teeny","label","fork","mask","discreet",
  "describe","flavor","malicious","steep","cannon","tax","elderly","minute","garrulous",
  "pedal","longing","ashamed","grey","grotesque","wish","jaded","choke","instruct","purring",
  "buzz","horrible","word","route","same","aggressive","sleep","answer","nest","nation",
  "spotted","foregoing","animated","straight","ocean","detail","lazy","hydrant","crabby",
  "macho","languid","silk","apologise","support","red","faulty","second-hand","secretive",
  "nippy","pickle","existence","steadfast","grain","smash","flimsy","shaky","woman",
  "library","kind","cheat","impartial","expansion","helpless","sigh","reminiscent","green",
  "subsequent","blot","drain","unequal","laborer","peep","vessel","untidy","alarm","ill",
  "need","health","next","airport","aback","able","fantastic","cloudy","pick","search",
  "gun","maniacal","tough","corn","pinch","vast","drum","magical","appreciate","camera",
  "overwrought","venomous","dazzling","live","cowardly","pull","female","like","frogs",
  "cute","babies","cattle","surprise","silent","cheer","metal","pig","mute","claim",
  "standing","godly","stroke","awful","greedy","guard","historical","noisy","recognise",
  "repulsive","behavior","reaction","bore","shivering","earsplitting","cut","bored","bird",
  "breezy","rob","division","blow","drip","river","kindhearted","handsomely","few","fairies",
  "ill-fated","tedious","ball","synonymous","callous","treat","nebulous","finger","sidewalk",
  "honorable","stretch","arrange","oafish","event","suppose","swanky","number","twist",
  "brown","great","greasy","disagree"
];

export function generateGameName() {
  const pick = () => {
    const w = words[Math.floor(Math.random() * words.length)];
    return w.charAt(0).toUpperCase() + w.slice(1);
  };
  return `${pick()} ${pick()} ${pick()}`;
}

export default words;